blank_issues_enabled: false
contact_links:
  - name: Fasm.ga Support
    url: https://github.com/fasmga/fasmga/discussions/categories/support
    about: If you have any questions about Fasm.ga, ask them there!
